# Generated by Django 3.1.6 on 2022-08-20 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0042_auto_20220820_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_user',
            name='floral_service',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='order_user',
            name='gravesite_service',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='order_user',
            name='prayer_service',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='flowertaker',
            name='flower_shops',
            field=models.CharField(choices=[('CF', 'Citfora Flowers'), ('GF', 'Gertudes Flowershop'), ('RG', "Raphael's Gifts"), ('LR', 'La Rose')], max_length=2, unique=True),
        ),
        migrations.CreateModel(
            name='FlowerTaker_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lapida_app.flowertaker')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapida_app.order_user')),
            ],
        ),
    ]
