# Generated by Django 3.1.6 on 2022-08-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0043_auto_20220820_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='floral_service',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='gravesite_service',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='prayer_service',
            field=models.CharField(max_length=1200),
        ),
    ]
