# Generated by Django 3.1.6 on 2022-08-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0048_auto_20220820_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowertaker_task',
            old_name='flowertaker',
            new_name='flower_taker',
        ),
    ]
