# Generated by Django 3.1.6 on 2022-08-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0049_auto_20220820_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_user',
            name='prayer_status',
            field=models.CharField(choices=[('P', 'Pending'), ('Ca', 'Cancelled'), ('C', 'Completed'), ('Pa', 'Paid'), ('O', 'Ongoing'), ('NT', 'Not taken'), ('NA', 'Did Not Avail'), ('NP', 'Not Paid')], default='NA', max_length=2),
        ),
    ]
