# Generated by Django 3.1.6 on 2022-08-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0051_auto_20220820_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='note',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
