# Generated by Django 3.1.6 on 2022-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0052_auto_20220820_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='flower_shop',
            field=models.CharField(blank=True, choices=[('CF', 'Citfora Flowers'), ('GF', 'Gertudes Flowershop'), ('RG', "Raphael's Gifts"), ('LR', 'La Rose')], max_length=2),
        ),
    ]
