# Generated by Django 3.1.6 on 2022-08-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0053_auto_20220820_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_user',
            name='image',
        ),
        migrations.AddField(
            model_name='order_user',
            name='after_gravesite_image',
            field=models.ImageField(blank=True, default='image/default_client.png', upload_to='image'),
        ),
        migrations.AddField(
            model_name='order_user',
            name='before_gravesite_image',
            field=models.ImageField(blank=True, default='image/default_client.png', upload_to='image'),
        ),
        migrations.AddField(
            model_name='order_user',
            name='floral_image',
            field=models.ImageField(blank=True, default='image/default_client.png', upload_to='image'),
        ),
        migrations.AddField(
            model_name='order_user',
            name='prayer_link',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
