# Generated by Django 3.1.6 on 2022-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0055_prayer_prayer_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='floral_status',
            field=models.CharField(choices=[('P', 'Pending'), ('Ca', 'Cancelled'), ('C', 'Completed'), ('Pa', 'Paid'), ('O', 'Ongoing'), ('NT', 'Not taken'), ('NA', 'Did Not Avail'), ('NP', 'Not Paid'), ('OV', 'Overdue')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='gravesite_status',
            field=models.CharField(choices=[('P', 'Pending'), ('Ca', 'Cancelled'), ('C', 'Completed'), ('Pa', 'Paid'), ('O', 'Ongoing'), ('NT', 'Not taken'), ('NA', 'Did Not Avail'), ('NP', 'Not Paid'), ('OV', 'Overdue')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='prayer_status',
            field=models.CharField(choices=[('P', 'Pending'), ('Ca', 'Cancelled'), ('C', 'Completed'), ('Pa', 'Paid'), ('O', 'Ongoing'), ('NT', 'Not taken'), ('NA', 'Did Not Avail'), ('NP', 'Not Paid'), ('OV', 'Overdue')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('Ca', 'Cancelled'), ('C', 'Completed'), ('Pa', 'Paid'), ('O', 'Ongoing'), ('NT', 'Not taken'), ('NA', 'Did Not Avail'), ('NP', 'Not Paid'), ('OV', 'Overdue')], max_length=2),
        ),
    ]
